nelmio_api_doc:
    documentation:
        info:
            title: Feedback
            description: The best app for feedback!
            version: 1.0.0
        servers:
            - url: /
              description: Servidor
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
